extends: minimal

users:
  home_base: /data/home
  default_groups:
    - sudo
    - docker

modules:
  docker:
    enabled: true
  nvidia:
    enabled: true
    gpu_allocation:
      enabled: true
      method: env
  cloudflared:
    enabled: true
    private_network:
      enabled: true
      interface: vlan0
      address: ""
  storage:
    enabled: true
  network:
    enabled: true
    ufw: true

ssh:
  disable_password_auth: true
